### PR TITLE
fix #432

### LINKED ISSUE #432: Logstash 2.0
Can i use the current cookbook for logstash version 2.0 ?

### PR DESCRIPTION
**Pull request by cyberflow**
This PR fix #432. Testing on 1.5.X and 2.X log stash versions

### CODE REVIEW

**Comment by willejs** [comment]
@lusis can you review and merge this please?

**Comment by willejs** [comment]
@paulczar can you merge this please?

**Comment by gsaslis** [comment]
+1 on having this merged in please. 

Ran into the same issue, and took me quite some time to work out what was causing it...

**Comment by martinb3** [comment]
Hi there! I've recently hopped in to help on this cookbook; if you'd like to rebase this against master, and have us review/merge it, please do so. If this PR is too out of date, and you think it should be closed, please do that as well. Thank you!

**Comment by martinb3** [comment]
Rebased and merged as b2aea1807c54ffe0a7e75c3dbf48afbfea3165ad.

**Pull request closed without merging**
