### PR TITLE
workaround to hardcode the min/max memory values

### PR DESCRIPTION
**Pull request by coffeepac**
this is because Ohai doesn't always set the values in the memory
top level node key.

### CODE REVIEW

**Comment by coffeepac** [comment]
@lusis anything else you'd like me to do in this PR?  I'm planing on adding generalized windows support for this cookbook so anything else you'd like (comments, docs, tests) would be good to know now.

thanks

**Comment by martinb3** [comment]
Hi there! I've recently hopped in to help on this cookbook; if you'd like to rebase this against master, and have us review/merge it, please do so. If this PR is too out of date, and you think it should be closed, please do that as well. Thank you!

**Comment by coffeepac** [comment]
@martinb3 I'm not even sure I have write permissions for that fork anymore, I left that gig awhile ago.  It looks like it'll merge clean but I don't have a way to test this anymore.  I also don't know if this is still a problem.  If no one else hit this I guess close it?

**Comment by martinb3** [comment]
Thanks @coffeepac -- I've rebased, squashed, and merged this into 3918dabf28c52ed8e0d4922eaaa6db29faefc5a9. Thanks again!

**Pull request closed without merging**
