### PR TITLE
Use a versioned directory structure

### PR DESCRIPTION
**Pull request by elyscape**
This makes the Logstash instances get deployed to (for example) `/opt/logstash/1.5.4/agent`. This was done because installing different versions on top of each other can cause weird, unexpected issues that are difficult to track down; installing Logstash 1.4.3 on top of Logstash 2.1.0, for instance, results in a Logstash instance that appears to work except that grok doesn't do anything. For compatibility with any other tooling written around the cookbook, as well as to simplify management of things like init scripts, a symlink is placed in (for example) `/opt/logstash/agent` pointing to the desired version (e.g. `/opt/logstash/1.5.4/agent`).

To deal with instances set up with a previous version of the cookbook, existing instances installed directly into (for example) `/opt/logstash/agent` will have their directories removed and replaced with symlinks to the new location.

### CODE REVIEW

**Comment by npilch** [comment]
Note that the tests here were failing before this pull request was made.

**Comment by johnr-spindance** [comment]
This is a good and much needed change, allowing the ability to use this cookbook to run a clean in-place upgrade of the logstash binaries. :+1:

**Comment by elyscape** [comment]
Pinging @lusis and @paulczar for review.

**Comment by elyscape** [comment]
@martinb3 Rebased.

**Comment by elyscape** [comment]
Rebased again from the force-pushed master.

**Comment by martinb3** [comment]
Hi @elyscape -- no worries, I can rebase it again if there's no changes. Just trying to get the existing master to pass 👍

**Pull request merged**
